export const enum EnvKey {
  LOG_MONIT = "LOGMONIT",

  HEARTBEAT_INTERVAL_APP = "HEARTBEAT_INTERVAL_APP",
  HEARTBEAT_PATH_APP = "HEARTBEAT_PATH_APP",
  HEARTBEAT_INTERVAL_CHILD = "HEARTBEAT_INTERVAL_CHILD",
  HEARTBEAT_PATH_CHILD = "HEARTBEAT_PATH_CHILD",

  AR20_PIN = "AR20_PIN",
  AR20_DEBOUNCE = "AR20_DEBOUNCE",

  SERIAL_PIN = "SERIAL_DATA_PIN",

  SERIAL_CLK_PIN = "SERIAL_CLK_PIN",
  SERIAL_CLK_DEBOUNCE = "SERIAL_CLK_DEBOUNCE",

  LED_A_PIN = "LED_A_PIN",
  LED_B_PIN = "LED_B_PIN",
  LED_C_PIN = "LED_C_PIN",
  LED_D_PIN = "LED_D_PIN",

  DB_SOCKET_PATH = "DB_SOCKET_PATH",
  DB_STORAGE_PATH = "DB_STORAGE_PATH",
  DB_BATCH_INTERVAL = "DB_BATCH_INTERVAL",
}

export const enum LedGpioName {
  Green,
  Red,
  Blue,
  Test,
}

export const enum ReceiverGpioName {
  AR20,
  SERIAL,
  SERIAL_CLK,
}
