export const enum EnvKey {
  AR20_PIN = "AR20_PIN",
  AR20_DEBOUNCE = "AR20_DEBOUNCE",

  SERIAL_PIN = "SERIAL_DATA_PIN",

  SERIAL_CLK_PIN = "SERIAL_CLK_PIN",
  SERIAL_CLK_DEBOUNCE = "SERIAL_CLK_DEBOUNCE",
}
